dist: trusty
sudo: required
before_install:
  - gpg --recv-keys 'E1CF20DDFFE4B89E802658F1E0B11894F66AEC98'
  - gpg --armor --export 'E1CF20DDFFE4B89E802658F1E0B11894F66AEC98'|sudo apt-key add -
  - sudo add-apt-repository 'deb http://deb.debian.org/debian/ stable main non-free contrib'
  - sudo apt-get -qq update
  - sudo apt-get install -y devscripts equivs
  - dch -r -m ''
  - >
    mk-build-deps -s sudo --install
    --tool "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends"
     debian/control
script:
  - make; make test
notifications:
  irc:
    channels:
      - "irc.oftc.net#debbugs"
  email: false
