dist: trusty
services:
  - docker
sudo: required
before_install:
  - docker build -t debbugs/travis -f .travis/Dockerfile .
script:
  - docker run debbugs/travis sh -c 'cd /debbugs/; make; make test'
notifications:
  irc:
    channels:
      - "irc.oftc.net#debbugs"
  email: false
