dist: trusty
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y devscripts equivs
  - dch -r -m ''
  - mk-build-deps -s sudo -i debian/control
script:
  - make; make test
notifications:
  irc:
    channels:
      - "irc.oftc.net#debbugs"
  email: false
