#!/bin/sh

set -e
if [ $# != 1 ]; then echo >&2 'need version'; exit 1; fi
version="$1"; shift
tag="`echo \"release-$version\" | sed -e 's/\./-/g'`"
cvs -Q tag -F "$tag"

cd ..
rm -rf bugs-export-temp$$ "debbugs-$version"
rm -f "debbugs-$version.tar" "debbugs-$version.tar.gz"
mkdir bugs-export-temp$$
cd bugs-export-temp$$

cvs -Q co -r "$tag" bugsdb
mv bugsdb "../debbugs-$version"
cd ..
rm -rf bugs-export-temp$$

tar	--exclude CVS \
	--exclude ncipher \
	--exclude '*.out' \
	--exclude '*.trace' \
	--exclude '*.new' \
	--exclude '*~' \
	--exclude 'trace' \
	-cf "debbugs-$version.tar" "debbugs-$version"
gzip -9 "debbugs-$version.tar"
rm -rf "debbugs-$version"
echo "../debbugs-$version.tar.gz created."
