#! /bin/sh
set -e

cd /org/bugs.debian.org/versions/indices

../bin/build-versions-db versions.idx versions_time.idx \
			 /etc/debbugs/indices/ftp \
			 oldstable stable proposed-updates \
			 testing \
			 testing-proposed-updates \
			 unstable \
			 experimental;
